name: Bot Trader Bolsa

on:
  # 1. Gatilho de Push: Obriga o GitHub a "acordar" o agendador assim que você salvar
  push:
    branches: [ "main" ]
  
  # 2. Agendamento Otimizado (Sweet Spot):
  # Roda nos minutos 03, 18, 33 e 48 para fugir do engarrafamento dos minutos redondos
  schedule:
    - cron: '3,18,33,48 * * * *'
  
  # 3. Botão Manual
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Permissão para o robô salvar arquivos no repositório
    permissions:
      contents: write

    steps:
      - name: 1. Baixar código
        uses: actions/checkout@v3

      - name: 2. Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 3. Instalar bibliotecas
        run: pip install -r requirements.txt

      - name: 4. Rodar Robô
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py

      - name: 5. Salvar Memória e Logs
        run: |
          git config --global user.name "Bot Trader"
          git config --global user.email "bot@github.actions"
          
          # Adiciona os arquivos de memória e log
          git add memoria_alertas.json historico_robo.txt
          
          # Tenta commitar. O "|| echo" evita erro se não houver mudanças
          git commit -m "Auto: Atualizando histórico [skip ci]" || echo "Nada para salvar"
          
          # Previne erro de conflito baixando atualizações antes de enviar
          git pull --rebase --autostash
          
          # Envia para o repositório
          git push
